name       : python-hyperlink
version    : 20.0.1
release    : 4
source     :
    - https://github.com/python-hyper/hyperlink/archive/v20.0.1.tar.gz : e5f63acc71a754e25a11aa436434f4f6087e42c01bd02afe1ded6879796a8341
homepage   : https://github.com/python-hyper/hyperlink
license    : MIT
component  : programming.python
summary    : Cool URLs that don’t change
description: |
    Hyperlink provides a pure-Python implementation of immutable URLs. Based on RFC 3986 and 3987, the Hyperlink URL makes working with both URIs and IRIs easy.
builddeps  :
    - python-idna
    - python-pytest
rundeps    :
    - python-idna
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3 -v
