name       : python-hyperlink
version    : 19.0.0
release    : 3
source     :
    - https://github.com/python-hyper/hyperlink/archive/v19.0.0.tar.gz : 277c33e9b74ea6aaac8c133e9e40e8d1f4b807cb4f78ad5be111c3be860aad74
license    : MIT
component  : programming.python
summary    : Cool URLs that don’t change
description: |
    Hyperlink provides a pure-Python implementation of immutable URLs. Based on RFC 3986 and 3987, the Hyperlink URL makes working with both URIs and IRIs easy.
builddeps  :
    - python-idna
    - python-pytest
    - python-setuptools
rundeps    :
    - python-idna
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
check      : |
    pushd $PKG_BUILD_DIR/py2build
        py.test
    popd

    pushd $PKG_BUILD_DIR/py3build
        python3 setup.py test
        py.test3
    popd
