name       : python-hyperlink
version    : 17.3.1
release    : 1
source     :
    - https://github.com/python-hyper/hyperlink/archive/v17.3.1.tar.gz : 16bcacf3a7cc1ce191b871d1ccf1573e53ab2e40235e6c16a3284c2a5ca3fb31
license    : MIT
component  : programming.python
summary    : Cool URLs that don’t change
description: |
    Hyperlink provides a pure-Python implementation of immutable URLs. Based on RFC 3986 and 3987, the Hyperlink URL makes working with both URIs and IRIs easy.
builddeps  :
    - python-pytest
    - python-setuptools
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
check      : |
    pushd $PKG_BUILD_DIR/py2build
        py.test
    popd

    pushd $PKG_BUILD_DIR/py3build
        python3 setup.py test
        py.test3
    popd
